### PR TITLE
Release config for Mac

### PR DESCRIPTION
**Pull request by markusstoll**
This is a proposal to have a build configuration that enables to have an automated build from jenkins for creating a Mac OS Executable.
I do not know how builds from command line work on Windows and Linux, so I did not create a build configuration for these.

This command will successfully build an OSX binary:

/Applications/Xamarin\ Studio.app/Contents/MacOS/mdtool -v build "--configuration:ReleaseMac"  <pathto>/SparkleShare/SparkleShare.sln

### CODE REVIEW

**Comment by hbons** [comment]
Nice! Does this trigger checkGit.sh? git and git-bin will need to be bundled, or is this solely for testing the build?

**Comment by markusstoll** [comment]
yep, it completely does, what a Xamarin build does within UI

**Comment by markusstoll** [comment]
Hm, but either (compiling from Xamarin and compiling it via command line) does not put the git build in the proper place. I have to dig into this

**Comment by markusstoll** [comment]
Well, the referred git version 2.9.2 is not compiling properly on my OSX systems (el capitan and sierra), still searching...

**Comment by markusstoll** [comment]
well, git 2.9.x had compilation problems. 
With git 2.10.0 the whole stuff works
still have problems with the resulting SparkleShare binary
still searching

**Comment by markusstoll** [comment]
I had SparkleShare compile from Xamarin and from commandline - seems to work fine with this pull request

**Comment by hbons** [comment]
Thanks a lot! Will set up a jenkins when I get back from holiday. :)

**Pull request merged**
