### PR TITLE
Squirrel integration

### LINKED ISSUE #622: Implement custom installer using Shimmer
designs: https://github.com/hbons/SparkleShare-Design-Corner/blob/master/desktop/windows-installer.png

### PR DESCRIPTION
**Pull request by BarryThePenguin**
- changed to .NET 4.5
- added nuget
- added nuspec file for releases
- ignored nuget related files
- added build process for squirrel packages

Now with all the benefits of [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows)
Will fix #622

ToDo:
- [ ] Create migration process from WiX to Squirrel
- [x] Figure out releases from [AppVeyor](http://www.rhysgodfrey.co.uk/b/blog/archive/2014/10/15/creating-github-releases-with-powershell) to GitHub?
- [ ] Create a loading .gif for installation process
- [x] Handle ssh-agent process on installation/upgrade/uninstall
- [x] Manage user data between releases Squirrel/Squirrel.Windows#47
- [x] Provide install/upgrade path for windows protocol handlers
- [x] Manage other installation related events (onInitialInstall, onAppUpdate, onAppUninstall, onFirstRun)
  - [x] "Run SparkleShare on Startup" is part of the SparkleSetup and may need modification?
  - [x] Add custom protocol handling on Install/Update, remove on Uninstall

### CODE REVIEW

**Comment by hbons** [comment]
happy new year! anything else that needs to happen here except for the animated GIF?

**Comment by BarryThePenguin** [comment]
Need to update to [Squirrel 0.7.2](https://github.com/Squirrel/Squirrel.Windows/releases/tag/0.7.2)

Getting AppVeyor working too would be the final step. They are now able to do releases to GitHub. I'll put together some instructions to get an "official" build server up and running. It would be good if the Squirrel release was as close too done as possible.

I was also wanting to release Sparkle.Lib as a nuget package too. I have another project which could make use of it.

**Comment by BarryThePenguin** [comment]
[Success!](https://github.com/BarryThePenguin/SparkleShare/releases/tag/1.5.0)

**Comment by hbons** [comment]
:+1:

**Comment by BarryThePenguin** [comment]
I'm still keen to get this merged. Appveyor is just a nice to have

**Comment by hbons** [comment]
Yes, I'd love to have this too. Can you rebase this on master please? It's had a lot of changes and I'm going to break everything for 2.0. :)

We no longer use ssh-agent, so that makes it a bit easier.

**Pull request closed without merging**
