### PR TITLE
Fix for running under sierra and above

### PR DESCRIPTION
**Pull request by markusstoll**
San Francisco font is not really accessible for app developers.

So we should always use Helvetica Neue with newer osx releases

### CODE REVIEW

**Comment by hbons** [comment]
How is it not available? It works here.

**Comment by markusstoll** [comment]
Hi, I have 3 sierra installations and the named font is not available on all of them.
I did some googling on this issue and from this I got the impression that this San Francisco font is not available to app developers and users by intention
How did you get this font?

**Comment by jmatsushita** [comment]
Hi there,

Also trying to build from source on Sierra and got the following stack trace which was also caused by `SF UI Text` not being present on my machine.
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.
Parameter name: value
  at (wrapper managed-to-native) MonoMac.ObjCRuntime.Messaging:void_objc_msgSend_intptr_intptr_bool (intptr,intptr,intptr,intptr,bool)
  at MonoMac.Foundation.NSObject.InvokeOnMainThread (MonoMac.Foundation.NSAction action) [0x00024] in <c30a4013b0494fb599f581fe5b9c885f>:0 
  at SparkleShare.Controller.Invoke (SparkleShare.Controller+Code code) [0x00013] in <44c1972c287649c2a7fd961b8602d48d>:0 
  at SparkleShare.UserInterface..ctor () [0x00006] in <44c1972c287649c2a7fd961b8602d48d>:0 
  at SparkleShare.SparkleShare.Main (System.String[] args) [0x0011e] in <44c1972c287649c2a7fd961b8602d48d>:0 
```

Hope this helps!

**Comment by hbons** [comment]
Looks like this is indeed an issue. I don't want to merge this yet though, as the WebView used by the event log may pick up on this font name and default to some ugly serif font. Need to investigate.

**Comment by hbons** [comment]
After some googling I found out the system font can be set like this: https://github.com/hbons/SparkleShare/commit/bdd38b45b10c66143f43c0aefb4403a5e18927a1

@markusstoll You were indeed right, I had the SF UI Text font manually for work purposes so I didn't see this issue.

Also, why the hell does this issue have so much noise? Must be a GitHub bug... :)

**Pull request closed without merging**
