### PR TITLE
updated linux app icon

### PR DESCRIPTION
**Pull request by snwh**
Original icon was based on the GNOME/Adwaita folder set, updated the SparkleShare icons to match the latest version of that set

### CODE REVIEW

**Comment by aggsol** [comment]
The star is way weaker and less prominent, it is harder to recognize than the old version.

**Comment by snwh** [comment]
@aggsol thanks, I missed grabbing an element when copying it from the source of the old one.

**Comment by hbons** [comment]
Sweet. Thanks!

**Comment by hbons** [comment]
@snwh can you provide the source file as well?

**Comment by snwh** [comment]
@hbons I did, it's in the Sources folder.

**Comment by hbons** [comment]
@snwh ah cool, missed it. Thanks again. :)

**Pull request merged**
