### PR TITLE
Remove usage of ServicePointManager.ServerCertificateValidationCallback ...

### PR DESCRIPTION
**Pull request by BarryThePenguin**
...by using HttpWebRequest

~~Requires .NET 4.5~~

### CODE REVIEW

**Comment by hbons** [comment]
it's a better way of doing it, but we can't assume w e have .NET 4.5 on Linux.
also, why's the Github check in there?

**Comment by BarryThePenguin** [comment]
Is there any way to find out?

Another option. If ServerCertificateValidationCallback is only required for Linux, we can exclude it for Windows. Or make it so we don't override the default callback by storing it in a temp variable.

The GitHub check is for the Squirrel updates, I may not include it though...

**Comment by hbons** [comment]
what problem are you trying to solve here? is there a downside the way it currently is?

**Comment by BarryThePenguin** [comment]
Changing ServicePointManager changes the default behaviour for the application. Any additional libraries (Squirrel) now fall over when trying to make https requests to sites other than Gravatar. That's why I included GitHub initially

**Comment by hbons** [comment]
ok, so we probably need to add #ifdefs here, so that this only happens on Windows.

**Comment by BarryThePenguin** [comment]
Added ifdefs for MonoCS as we don't want ServerCertificateValidationCallback to be used on Windows.
Also Resharper decided to do it's thing...

**Comment by knocte** [comment]
Why are there so many whitespace changes here?

**Comment by BarryThePenguin** [comment]
Resharper... I can do another commit to change them if need be

**Comment by knocte** [comment]
Please fix them, and then squash the commits into one.

**Comment by BarryThePenguin** [comment]
[Fact of the day](https://github.com/blog/967-github-secrets), adding ?w=1 to the URL removes white space from the diff

**Comment by BarryThePenguin** [comment]
There we go, hopefully that's a bit clearer. Better aligns with the [coding style](https://github.com/hbons/SparkleShare/wiki/Coding-style) too

**Comment by knocte** [comment]
I still see some whitespace changes.

**Comment by BarryThePenguin** [comment]
Yup! There's an extra space I removed and some tabs that I converted to spaces. All intentional

**Comment by knocte** [comment]
Not sure what Hylke thinks, but I would propose those changes in a separate commit and separate PR. The less noise a PR has, the better. More info: http://tirania.org/blog/archive/2010/Dec-31.html

**Comment by BarryThePenguin** [comment]
Absolutely. I agree.

In addition though, if a tool such as Visual Studio or Resharper makes changes automatically to a file a contributor is working on, is it reasonable to expect them to go back and reverse those changes? Especially if those changes reinforce the coding style specified by the project? I see coding styles as a necessary hinderance. That's why we have tools such as [EditorConfig](http://editorconfig.org/).

Am happy to open a new PR though with the whitespace changes if it will speed up the process.

**Comment by BarryThePenguin** [comment]
To add to my comments above, coming from M$ land with Visual Studio I found the current coding style a huge hurdle to contributing to SparkleShare. Visual Studio does the complete opposite of what the coding style requests. I spent a lot of time trying to force it to better adhere to the coding style so that other contributors in the same position as me would have a better experience trying to contribute to the project.

**Comment by knocte** [comment]
> In addition though, if a tool such as Visual Studio or Resharper makes changes automatically to a file a contributor is working on, is it reasonable to expect them to go back and reverse those changes?

No need to do that. What the contributor needs to do is include in his commit only the real changes. (For example, to choose certain parts of a file to be included in a commit and not others, I use a very useful tool called `git gui`.)

> To add to my comments above, coming from M$ land with Visual Studio I found the current coding style a huge hurdle to contributing to SparkleShare.

Every project out there uses its own coding style. For example, I myself contribute to MonoDevelop which uses tabs, and to banshee which uses spaces. The way to deal with this, in my case, is use an IDE that supports specifying coding-style settings at the solution-file level (which is supported by MonoDevelop itself, I strongly recommend you to try this IDE instead of Visual Studio).

> Am happy to open a new PR though with the whitespace changes if it will speed up the process. 

Great! Thanks for your contribution.

**Comment by hbons** [comment]
`git add --patch` is very helpful. :)

**Comment by BarryThePenguin** [comment]
So much git. This should be good to go now. No longer relies on .net 4.5

**Comment by hbons** [comment]
thanks!

**Pull request merged**
