### PR TITLE
Unit testing for SparkleLib with basic coverage reporting

### PR DESCRIPTION
**Pull request by BarryThePenguin**
- Added unit testing and coverage report ([xunit2](https://github.com/xunit/xunit), [AutoFixture](https://github.com/AutoFixture/AutoFixture), [OpenCover](https://github.com/OpenCover/opencover) and [ReportGenerator](https://github.com/danielpalme/ReportGenerator))
- Included nuget
- Added a simple test for SparkleFolder
- Made SparkleFolder depend on DirectoryInfo API (Name, FullName etc)
- Removed SparkleFolder dependency on SparkleConfig.DefaultConfig
  - SparkleLogger is also dependant on DefaultConfig so falls over if DefaultConfig hasn't been set. I added a null check but it would be good if this didn't need to happen...
- Extracted SparkleConfig out as an Interface (creating a Fixture for XmlDocument is a Bad Idea)
- Moved SparkleConfig initialisation out of the Controller and into Program.Main()

The main aim of this pull request is initiate the removal of the dependency on SparkleConfig.DefaultConfig, supporting that process with unit testing and to open a path towards better dependency injection.

Example coverage report
image

It'd be good to know if you think this is something that would be beneficial to SparkleShare or not.

### CODE REVIEW

**Comment by hbons** [comment]
Can you explain to me a bit more about the tests? I've no idea how this stuff works. :)

**Comment by BarryThePenguin** [comment]
I'll try and be specific.

- `SparkleFolderTests` is testing the `SparkleFolder` class.
- `SparkleFolder` has a dependancy on `SparkleConfig`. As `SparkleConfig` inherits `XmlDocument` I created the `ISparkleConfig` interface which allows us to create a fixture to use during testing. That's the purpose of `SparkleConfigFixture`.
- The two test methods in `SparkleFolderTests` check that `SparkleFolder.GetInfo` returns the a valid path to a SparkleShare folder, both in the default SparkleShare directory and a custom SparkleShare directory.
- The AutoData Attribute allows injecting fixtures into tests. These are the `string folder_name` and the `SparkleFolder folder`. The tests are performed using these fixtures.
- The test then uses the Assert method to make sure the actual `result` matches our expected result (`expected_full_path`)
- Each test then cleans up the test Config folder that was created during the test.

Ideally, we should be able to test each class independently. Any dependencies a class has, we should be able to create a fixture for and inject into that class. By injecting dependencies in this way, we can setup fixtures in a way that we can test for successful scenarios as well as exceptional scenarios.

**Comment by BarryThePenguin** [comment]
Let me know if I need to clear anything up. Happy to answer questions, or break it into smaller pull requests.

**Comment by aggsol** [comment]
So this is no longer coming to SparkleLib?

**Pull request closed without merging**
