### PR TITLE
macOS increase .Net version to 4.8

### PR DESCRIPTION
**Pull request by markusstoll**

### CODE REVIEW

**Comment by hbons** [comment]
Looks like this breaks the CI. Is this really needed right now?

**Comment by markusstoll** [comment]
Hm, could it be that on travis the latest version of VisualStudio is missing?

I guess its not really needed, but..

Until now me and my colleagues have been using SparkleShare 3.28 and we sometimes do observe some strange phenomena. This is the whole reason why I was digging into building Version 3.38 and fixing all bugs I observed. 
By bumping the versions for git and .Net I just wanted to avoid having unnecessary bugs from old stuff. 
So maybe .Net 4.7.2 is good enough...

**Comment by knocte** [comment]
.NET4.7.2->4.8 doesn't really introduce bugfixes but features, and not all versions of Mono support 4.8 (e.g. versions from stable Debian). IMO this change should only happen if it fixes a specific problem, not "just in case".

**Comment by markusstoll** [comment]
@knocte My proposed change is related to macOS only - still I think .Net 4.5 is way too old

**Comment by knocte** [comment]
I've never thought of .NET Framework versions as old or new. They are just versions. What is usually too old are the runtimes that run these .NETFramework versions (e.g. Mono).

But anyway now I checked the diff and see you only changing this in one project, which shouldn't affect Linux. However the fact that it breaks CI is concerning (maybe because the Mono version that runs on Mac still doesn't support 4.8). Maybe upgrade to 4.7.2 to see if it fixes CI?

**Comment by markusstoll** [comment]
Ok, Travis does not know about .Net V4.7.2 either - so I guess we close this for now as long this not really needed

**Pull request closed without merging**
