### PR TITLE
Fedora 27 - making it start and run

### PR DESCRIPTION
**Pull request by glunardi**
Probably not the best way to handle the startup issues on Fedora 27 but it would seem like the differences in "GNOME" and Ubuntu versions interpreted here have changed.

Removing the special cases and handling F27 the same way Ubuntu is seems to allow SparkleShare to start.

Also proposing to add the libtool.m4 file to .gitignore.

### CODE REVIEW

**Comment by glunardi** [comment]
About dialog window without the patch on F27 (GNOME):
about-window-before-patch

About dialog window with patch applied
about-window-after-patch

**Comment by glunardi** [comment]
I could not figure out a way to split the commits either when I submitted (some weird github specificity?).

The issue on startup for F27 seems to be there for a local build or the flatpak: The GLib.Application.run call goes out but never completes. It just hangs there, the mono process never gets a callback or anything. 

Actually I just remembered that the code won't even compile with the logic that is there (master) now on F27 against their version of glib/gio foo. It complains with:

./UserInterface.cs(76,39): error CS1502: The best overloaded method match for `GLib.Application.Run(int, string)' has some invalid arguments
/usr/lib64/pkgconfig/../../lib/mono/gtk-sharp-3.0/gio-sharp.dll (Location of the symbol related to previous error)
./UserInterface.cs(76,44): error CS1503: Argument `#1' cannot convert `string' expression to type `int'

So I suppose things definitely changed somewhere but I have not looked further (needed to get it going because of a deadline)

**Comment by glunardi** [comment]
Could you use this page (on the web ui) to accept just one commit from the pull request? Just got curious about this all of a sudden;

https://github.com/hbons/SparkleShare/pull/1791/commits/1b25f0c83f8c8f47b21b7e4596064b0238473c20

**Comment by hbons** [comment]
#1803 will fix the compile issue with the Run method. I've taken all your changes that are useful from here (no directly the commits). Will look at the WebKit issue soon. Thanks!

**Pull request closed without merging**
