### PR TITLE
Update Checkgit.sh

### PR DESCRIPTION
**Pull request by orien3243**
I did a rough sketch of how this would work. Please consider changing revising where appropriate.

- What does this change do?

Basic checking of sha256 of a file. My change calculates the hash of the file it downloads and also downloads a list of hashes, we then compare the first 64 characters, the hash, that the pc calculates to the hash it downloaded. 

Should there be a mismatch or if a file fails to download, the script will exit 1.

ps.
I'm not sure if the script should eval the hashes right before it compares them or if the way I evaluate the variables is ok. Also I did not use grep as I have been told it was bad.

### CODE REVIEW

**Comment by hbons** [comment]
Awesome. :)
I don't think we need the download of the hash lists. I'd like to just keep our own copy in case someone messes with the file upstream. Can you just put the hashes file in the tree and remove the download?

**Comment by orien3243** [comment]
based on what I read, all I need to do is upload the file to where checkgit.sh is and remove the curl download, correct? 

I uploaded the file on my working tree, created a pull request for. Sorry if I seem a bit unsure but I'm new to this.

**Comment by hbons** [comment]
Yep, that's it! Can you include sha256sums.asc in the commit?

**Comment by hbons** [comment]
Ah, I see you did that in another pull request. Thanks so much! :)

**Pull request merged**
