### PR TITLE
updated gravatar cert fingerprint

### LINKED ISSUE #1900: Invalid certificate for https://www.gravatar.com/
Running Ubuntu Bionic 18.04 LTS on x86_64-linux-gnu. AMD Ryzen 2500. 16GB Ram, 1TB SSD boot drive with additional HDD drives...

**FROM THE LATEST LOG:**
11:22:55 Environment | SparkleShare 3.28.0 (Flatpak)
11:22:56 Environment | Git LFS 2.4.0
11:22:56 Environment | Git 2.17.0
11:22:56 Environment | Ubuntu (Linux 4.15.0.46)
11:22:58 Environment | GTK+ 3.22.30
11:22:58 Environment | Status Icon: AppIndicator

**THE ERROR:**
11:23:04 Avatars | Invalid certificate for https://www.gravatar.com/
11:23:04 Avatars | Error fetching avatar for <my-correct-email-address>: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED)   at System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) [0x0008a] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 
  at System.Net.WebClient.DownloadData (System.Uri address) [0x00029] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 
  at System.Net.WebClient.DownloadData (System.String address) [0x00019] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 
  at (wrapper remoting-invoke-with-check) System.Net.WebClient:DownloadData (string)
  at SparkleShare.Avatars.GetAvatar (System.String email, System.Int32 size, System.String target_path) [0x00160] in <cc5d93e6b2c7414faa51c74d720c34aa>:0 

### What happened:
Of course, no Avatar appears

### What I expected to happen:
Normal execution with avatar displayed

### This happens when:
Anytime SparkleShare is run

Thanks for reporting your issue or feature request, it helps lots!

### PR DESCRIPTION
**Pull request by MalteKiefer**
fix #1900

### CODE REVIEW

**Comment by hbons** [comment]
The reporter in #1900 also mentioned the app stopped running? This shouldn't happen, it would be great if this exception could be caught somehow.

**Comment by MalteKiefer** [comment]
My question is why we we checking the fingerprint?I mean Gravatar will never get a cert error or? Am Sa., Okt. 31, 2020 um 12:28, Hylke Bons <notifications@github.com> schrieb:  
The reporter in #1900 also mentioned the app stopped running? This shouldn't happen, it would be great if this exception could be caught somehow.

**Comment by MalteKiefer** [comment]
My opinion is that we should remove it

**Comment by hbons** [comment]
As I remember it, I've added this because sometimes the local HTTPS certification check would sometimes break on some distros. It's possible it's not longer needed with Flatpak but it needs to be checked.

**Pull request merged**
