### PR TITLE
Windows merge

### PR DESCRIPTION
**Pull request by Klemele**
Update to make the Windows version work.
The initial work was done by @BarryThePenguin from #1703 , I simply update it with the recent changes.

Work not done from previous checklist : 

- [ ] Radio buttons with labels and descriptions for storage type selection page
- [ ] bundle git-lfs >= 1.3.0

### CODE REVIEW

**Comment by Klemele** [comment]
Error from appveyor comes from the Linux project, should I make another PR to update the SparkleShare.Linux.csproj, or directly adding a commit on this one with the fix ?

**Comment by Klemele** [comment]
@hbons news?

**Comment by hbons** [comment]
I didn't see this PR for some reason. I'll have a look soon!

**Comment by Klemele** [comment]
Just missing your review @hbons ;)

**Comment by Klemele** [comment]
Hello again @hbons, any news ? I'm a little bit pushy, because I am working on a desktop application, based on SparkleShare, for the opensource project LinShare. You can take a look to the latest development through our online demo (https://github.com/linagora/linshare#live-demo). We are close to releasing our product and it would be awesome if we can have at least the windows version of Sparkleshare to work. That's why this PR exist ;). So just if you can notice me of when you will have the time to review it, it would be awesome.  First PR, but clearly, not the last  ;)

**Comment by hbons** [comment]
@Klemele thanks!  Looks like a cool product. :)

**Comment by hbons** [comment]
@BarryThePenguin are the .config files in https://github.com/hbons/SparkleShare/tree/master/SparkleShare needed? If so, can you move tem to the Windows subfolder?

**Comment by BarryThePenguin** [comment]
Nah, they can be removed 👍

**Comment by hbons** [comment]
@BarryThePenguin thanks, gone.

**Pull request merged**
